name: Cross-compile for BBB

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-arm:
    runs-on: ubuntu-latest

    steps:
      # 1. Lấy source code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Cài đặt ARM toolchain
      - name: Install ARM cross compiler
        run: sudo apt-get update && sudo apt-get install -y gcc-arm-linux-gnueabihf

      # 3. Build hello.c cho ARM
      - name: Cross compile hello.c
        run: arm-linux-gnueabihf-gcc hello.c -o hello.elf

      # 4. Upload artifact (.elf)
      - name: Upload ARM binary
        uses: actions/upload-artifact@v4
        with:
          name: hello-arm-binary
          path: hello.elf
